/etc/apache2/sites-available/https.conf

<VirtualHost *:80>
    RewriteEngine on
    RewriteCond %{HTPS} !=on
    RewriteRule ^/?(.*) https://{SERVER_NAME}/$1 [R=301,L]
</VirtualHost>
<VirtualHost *:443>
    ServerName www.bibit.id

    DocumentRoot /var/www/web

    SSLEngine on
    SSLCertificateFile /etc/ssl/certs/web.crt
    SSLCertificateKeyFile /etc/ssl/private/web.key

    <Directory /var/www/lab>
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/lab_error.log
    CustomLog ${APACHE_LOG_DIR}/lab_access.log combined
</VirtualHost>
