##add new zone here for your domain##
/etc/bind/named.conf

zone "bibit.id" {
    type master;
    file "/etc/bind/db.domain";
};

zone "10.168.192.in-addr.arpa" {
    type master;
    file "/etc/bind/db.reverse";
};



